import type { Metadata } from 'next'
import { poppinsBold, poppinsMedium, poppinsLight } from '../src/utils/Font'
// These styles apply to every route in the application
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className={`${poppinsLight.variable} ${poppinsMedium.variable} ${poppinsBold.variable} font-poppinsLight`}
    >
      <body>{children}</body>
    </html>
  )
}
